# Generated by Django 6.0 on 2026-01-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('WAEC', 'WAEC'), ('NECO', 'NECO'), ('JAMB', 'JAMB')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration of exam in minutes')),
                ('total_marks', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
